# Generated by Django 4.0.4 on 2022-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
